version: '3'
services:
  movies:
    image: jabinmohammad/book:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: jabinmohammad/notebook:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: jabinmohammad/textbook:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: jabinmohammad/colourbook:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

